# Generated by Django 2.1.1 on 2018-10-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAsistencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=100),
        ),
    ]
